### ISSUE TITLE
add pagination for fetching posts

### ISSUE THREAD

**Issue by osmannkartall** [osmannkartall/knowzone#152]
It might be better, if it is done with scrolling rather than clicking. We can think of post screens as timelines.

**Comment by rkoleci** [comment]
assign this to me

**Comment by osmannkartall** [comment]
Without assignment, you should be able to fork the repository and create pull requests for your changes.

**Comment by rkoleci** [comment]
I think im gonna need a login test account ..

**Comment by osmannkartall** [comment]
If you mean an account for Azure, no you don' t need it. Application is not available as service, so you have only local options: Running via local cluster or running React, Node.js and MongoDB separately.

We used our limited Azure account for a demonstration of the production environment. We no longer have a subscription.

You can send me email(kartal.osman@outlook.com.tr) for further questions.
