### ISSUE TITLE
delete form and its posts

### ISSUE THREAD

**Issue by osmannkartall** [osmannkartall/knowzone#184]
- [x] @sametrozturk It can be implemented in formController.deleteById() function.
- [x] @sametrozturk Deleting form and its posts should be done in transactional block.
- [x] @sametrozturk Add Delete button in the header of Posts.jsx. Open a confirm dialog and send the request onClick confirm.
- [ ] @osmannkartall docker-compose
- [x] @sametrozturk fix the command https://github.com/osmannkartall/knowzone#mongodb

We can convert the standalone mongo instance to replica set with this change

```yaml
docker run -d \
    -p 27017:27017 \
    --name dev-mongo \
    -v dev-mongo-data:/data/db \
    -e MONGODB_INITDB_ROOT_USERNAME=user \
    -e MONGODB_INITDB_ROOT_PASSWORD=pass \
    mongo:latest \
    mongod --replSet rs0 \
    --bind_ip_all
```

References

- https://www.mongodb.com/community/forums/t/why-replica-set-is-mandatory-for-transactions-in-mongodb/9533
- https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/
- https://www.mongodb.com/docs/v6.0/core/security-mongodb-configuration/

**Comment by sametrozturk** [comment]
I'm currently working on it.
